### ISSUE TITLE
Neovim plugin: issue with toggling with :Ghcid

### ISSUE THREAD

**Issue by adelbertc** [ndmitchell/ghcid#102]
I'm starting the plugin with `:Ghcid --command="cabal repl exe:foo"` which opens up a window and does it's thing. I have checked that introducing an error causes it to reload and show the error in the editor.

However, when I run `:Ghcid` to toggle the window back down, I get something like:

```
Error detected while processing function 284:

Ghcid: Exited with status 1
```

I thought it might be referring to the line the function it's trying to call is on, but seems unrelated: https://github.com/ndmitchell/ghcid/blob/master/plugins/nvim/ftplugin/haskell.vim#L284

What's even weirder is that when I quit Neovim and do the same steps as above, the number increments by 2 each time?!?! It was 286, then 288, now its 290...

**EDIT**: After reading through the plugin code a bit am I correct in assuming the Ghcid buffer should be hidden if everything is OK? Right now when I run it I see "All good (2 modules)" but the buffer stays open. Which maybe is why it breaks when I try to close it because it thinks the buffer is closed already?

**Comment by cloudhead** [comment]
By default, it'll hide the window if everything is OK. There's an option to change that: https://github.com/ndmitchell/ghcid/blob/master/plugins/nvim/ftplugin/haskell.vim#L16

As you see, the option will keep the window open if `&hidden` is set to false, because closing the window would kill the buffer entirely. Could it be that your vim config doesn't allow hidden buffers? You can check with `:echo &hidden` - it should return `1` if hidden buffers are allowed.

**Comment by cloudhead** [comment]
I think this was fixed some time ago, please re-open if you're still having issues.
