### ISSUE TITLE
Default to exec'ing ghci in sandbox if present?

### ISSUE THREAD

**Issue by afcowie** [ndmitchell/ghcid#23]
It just took me the better part of an hour to remember how to use this. I tried

```
$ ghcid
$ cabal exec ghcid
$ ghcid tests/Experiment.hs
```

and many variations. You get the idea, I'm sure. What worked in the end was this:

```
$ ghcid --command="cabal exec ghci tests/Experiment.hs"
```

which, I think you'd agree, is a mouthful.

It would be nice if

a) ghcid was cabal sandbox aware, automatically using cabal exec to get into ghci [I gather it's a no-op in the absence of a sandbox, so perhaps that's viable as a default]

b) ghcid took an argument to be interpreted as a filename [or cabal repl target?] to be what is `:load`ed.

Am I totally missing the plot here? I know you can have a _.ghci_ file with commands in it, but that doesn't seem to be so great when you're quickly trying to build and test lots of different snippet test prorams.

AfC

**Comment by ndmitchell** [comment]
The problem with `cabal exec` is that it's slow, and in older versions, buggy (if there is any compile error it bails out rather than opening ghci with a compile error). What is the difference between `cabal exec` and `cabal repl`? Having arguments be `:load`ed seems like a reasonable idea, and might have been enough in conjunction with `cabal repl` to make your third command work.

**Comment by afcowie** [comment]
> The problem with cabal exec is that it's slow

Well, that's mitigated by the fact that the whole point of _ghcid_ would seem to be running the child GHCi process only once, so wrapping it in `cabal exec` isn't going to hurt. [Day to day I am running the above command via a shell script:

```
$ cat ~/.local/bin/build 
exec ghcid --command="cabal exec ghci $*"
$
```
thence `build tests/ThoughtExperiment.hs`, (because I keep trying to do `cabal exec ghcid`, which is wrong but seems reasonable)].

> What is the difference between `cabal exec` and `cabal repl`?

As far as I can tell, `cabal repl` will only load a named section from the _.cabal_ file (executable, test suite, or benchmark) and not just an arbitrary file — which **does** work with the pattern above

> Having arguments be :loaded seems like a reasonable idea, and might have been enough in conjunction with cabal repl to make your third command work.

Quite possibly, but type checking ad-hoc scripts is where this is really shining for me for the moment, and lord knows having to enumerate each and every junk test program in your _.cabal_ file just to repl it is tedious at best.

AfC

**Comment by ndmitchell** [comment]
One of the reasons I regularly stop/start my ghcid is to save my laptop battery, which I guess #26 is the real fix for. So I guess what we need is an algorithm to go from a directory with files in it, and optionally a list of files, to a command line and list of commands. Currently that algorithm is https://github.com/ndmitchell/ghcid/blob/master/src/Ghcid.hs#L51 and has no support for free command line arguments. It seems what you are suggesting is roughly:

* If you have a .cabal file in the directory, and no arguments, do `cabal repl`.
* If you have a .cabal file in the directory, and some arguments, do `cabal exec ghci <arguments>`.
* Otherwise, do `ghci <arguments>`

Does that seem about right?

One thing that seems not to work with that is that if I import `Paths_shake` into a module then `cabal exec` doesn't work, but `cabal repl` does. Any thoughts on how to avoid that?

**Comment by ndmitchell** [comment]
I've rewritten it, so now `ghcid tests/Experiment.hs` works, which will do a `cabal exec ghci tests/Experiment.hs` for you under the covers. Please let me know if there are still undesirable cases.
