### ISSUE TITLE
VSCode: Cannot find "Watch Ghcid output" command

### ISSUE THREAD

**Issue by Rizary** [ndmitchell/ghcid#239]
I tried running haskell project which create `ghcid-output.txt` and follow the instructions:
`Open ghcid.txt in VS Code as the active editor. Run the VS Code command (Ctrl+Shift+P) named "Watch Ghcid output".`

but I can't find the `watch ghcid output`

Does the command still there?

**Comment by ndmitchell** [comment]
This was removed in 9bd2a4718f57d459a1b4e2d4691139ab47d9dd9e. I should have cleaned up the documentation too. Although I'm wondering why it was removed, since that would have been rather handy for me some of the time. Were you hoping to use it? What's your use case for it? If so, I'll reinstate it and release.

**Comment by Rizary** [comment]
Hi @ndmitchell, so right now I am using obelisk project in my windows machine (WSL) and want to develop using VSCode installed in my windows. So whenever we run `ob watch`, it generates `ghcid-output.txt` and `watch ghcid output` is needed in this case iirc.

moreover, it has been discussed in https://github.com/obsidiansystems/obelisk/issues/184#issuecomment-457752765 also.

**Comment by srid** [comment]
I have been using this feature actually (when using vscode). `ob run` basically does a bunch of things and delegates to ghcid ([configuring it](https://github.com/obsidiansystems/obelisk/blob/master/lib/command/src/Obelisk/Command/Run.hs#L208) to output to a file called `ghcid-output.txt`), and I run `ob run` on terminal (outside of vscode).

**Comment by srid** [comment]
Slightly off-topic: I'd love to have this feature on Emacs (which is what I use right now) as well. :-)

**Comment by Rizary** [comment]
@srid that is good to hear. I think this feature is very useful.

**Comment by ndmitchell** [comment]
Have you seen the `ghcid command` setting? If you set that to `ob run` then starting Ghcid might work properly,. Would that be an easier route?

**Comment by aveltras** [comment]
Would be nice to have this option back. The problem faced here is when you have to enter a specific environment with nix or direnv for example which default "Start ghcid" doesn't seem to handle well. The watch option seems good to have since it's pretty environment agnostic relative to the way to generate the ghcid.txt.

**Comment by srid** [comment]
> Have you seen the ghcid command setting? If you set that to ob run then starting Ghcid might work properly,. Would that be an easier route?

@ndmitchell That setting doesn't seem to know how to run complex CLI like the following (which I use in a non-obelisk project):

```
nix-shell default.nix --run "cd example; ghcid -c 'ghci -Wall -i../src  Main.hs' -T 'Rib.App.dev Main.settings' --reload=Main.hs"
```

![image](https://user-images.githubusercontent.com/3998/61153796-521cc400-a4ba-11e9-9ccd-aa86ae637142.png)

**Comment by srid** [comment]
> The watch option seems good to have since it's pretty environment agnostic relative to the way to generate the ghcid.txt.

Yea. And sometimes I do want to leave ghcid running in a terminal inside tmux, so that I can reattach to my project environment from elsewhere without being tied to VScode.

**Comment by srid** [comment]
@ndmitchell Here's another reason to support 'Watch ghcid output'. I often pass `-T` to ghcid in order to *also* run the main program (which does stuff like start web server, spit out some logging info, etc.). If I relinquish control of the output of this ghcid to the vscode extension, there would be no way to see the logging output.

**Comment by srid** [comment]
Oh wait I take that back (deleting...)

**Comment by srid** [comment]
> That setting doesn't seem to know how to run complex CLI like the following

Okay I am able to work around this issue by putting the long CLI in a script file, and then using that script file in the vscode settings. Works now! (However I don't see error inlines; but that's outside the scope of this issue ...)

**Comment by ndmitchell** [comment]
I think the tmux argument is compelling. Definitely something to add back. PR welcome, or I'll get to it one day.

**Comment by srid** [comment]
Great! I wonder if we should resurrect this feature but provide a somewhat different (arguably improved) UX. That is:

- Have the user run ghcid writing to (say) `ghcid-output.txt` at project root (in fact, obelisk [does this by default](https://github.com/obsidiansystems/obelisk/blob/develop/skeleton/.gitignore#L7), without the user having to do anything; so `ob run` generates this file automatically)
- Have the user configure the VScode extension to specify `"${projectroot}/ghcid-output.txt"` as the filepath to ghcid output (instead of the executable path to ghcid itself, which would be the *alternative* option)

Then the extension can work **automatically** by reading the configured file, instead of the user having to **manually** open the said file. 

Just a suggestion, though.

**Comment by ndmitchell** [comment]
Makes a lot of sense @srid - I still like the menu entry "open with this file" (since that's the primitive), but having configuration options that let everyone just "start ghcid" makes a lot of sense. PR most welcome.

**Comment by endgame** [comment]
I think having ghcid watch file output solves another problem - trying to start ghcid once and for all in a single project is often not possible. The test suite usually has a different set of dependencies, and ghcid gets confused. In emacs-land, where I usually work, I have to tell my ghcid integration to use a different target based on the directory the source file is in.

**Comment by ndmitchell** [comment]
All sounds great. Patches welcome. I suspect I'm not likely to get to this in the near term, since I've stopped using the ghcid extension in favour of [ghcide](https://github.com/digital-asset/ghcide) where I can (somewhat to dogfood ghcide).

**Comment by chrismwendt** [comment]
Fix pending in https://github.com/ndmitchell/ghcid/pull/313
