### ISSUE TITLE
Default height hides file and line info

### ISSUE THREAD

**Issue by cocreature** [ndmitchell/ghcid#25]
If I start ghcid without arguments it scrolls to just below the line `src/Handlers.hs:19:52:` (or the line an error is found at). So I can see the warning but not the line info which makes the default pretty useless. If I specify the height manually it works just fine.

**Comment by cocreature** [comment]
Closing because I can't reproduce it anymore :/

**Comment by ndmitchell** [comment]
Well, great news that it fixed itself! I took a look, and to make it easier to debug next time, I've made it so that `--verbose` prints out the detected size/height of your console. Looking through that verbose log, I also spotted that I snapshot the size of the console, and then query ghci for more information. I've now moved the size request closer to where I use the size, so it may be that you fell into a race condition that has since been removed.
