### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by afcowie** [ndmitchell/ghcid#28]
Unfortunately our work to reduce wakeups in https://github.com/ndmitchell/ghcid/pull/27 doesn't work when the editor is vi[m]. _ghcid_ errors out with:
```
src/MostExcellentProgram.hs: Can't find file
```
the moment the source file in question is updated. Bummer.

When saving, some editors — like vi — write out a new file, then delete the original one and atomically move the replacement to the original's name (this avoids an interrupted write from leaving a corrupt half empty file).

The particular set of _inotify(7)_ flags I used in my original branch at #27 were specifically chosen to accommodate this case ("deleted", "closed write" in addition to "modified").

Since you've adopted **fsnotify**, we'll need to work out what the equivalent trick will be with that wrapper. At present _ghcid_ is unusable, unfortunately.

AfC

**Comment by afcowie** [comment]
Hm. And it's not something crazy I was doing; turns out its triggered if I do it the "approved" way, too:

```
$ ghcid -c "cabal repl experiment"
[first time]
All good
[second time]
tests/Experiment.hs: Can't find file
^C
$
```

**Comment by ndmitchell** [comment]
See also @thomie and #22, which is probably the same issue, but now made more symptomatic.

I can't reproduce this, even using VIM, but I am on Windows. The algorithm ghcid uses is to wait for file system notifications, use them to trigger a modtime scan on all the interesting files, and if they detect any changes then continue on. Once you continue on, record the modtime before reloading, and if after loading anything has a newer modtime, reload again (so you don't get races from things changing during reload).

My only guess can be that VIM writes out the tmp file, then deletes the real file, waits a little (40ms according to @thomie - during which time ghcid triggers) then does a rename. That rename doesn't trigger the race condition checking because it still has a modtime from before ghcid did the reload. To try and guard against that I now wait 1s if a file that was previously present, and I believe GHCi is actively looking at, has disappeared. That should give plenty of time for VIM to replace the file, and the extra latency should happen pretty rarely (deleting a loaded file is not a common operation), and only when you probably already know the code is broken.

Can you please test. I also added lots of logging, so `--verbose` will tell you about every event, and how ghcid decided to react. Regardless of if its fixed or not, it would be useful to get a `ghcid --verbose --height=3` log so I can see what VIM on Linux triggers (the `--height` is just to remove some redundant whitespace lines in the log).

**Comment by afcowie** [comment]
@ndmitchell Initial impression is that it's working now. Nice. But since we're not sure _why_ it's working, I will indeed get an operations trace with `-v` for you shortly.

**Comment by ndmitchell** [comment]
I found a bug in the waiting code. I did a reload, then marked that as the start of the wait transaction, but if you deleted the file, started the reload, and during the reload the file came back, it would have been missed. I suspect this might have been the underlying problem all along.
