### ISSUE TITLE
Nitpick: Your copyright has expired according to your license

### ISSUE THREAD

**Issue by umnikos** [ndmitchell/ghcid#294]
In LICENSE:
> Copyright Neil Mitchell 2014-2019.

I swear I saw this by accident :sweat_smile:

**Comment by ndmitchell** [comment]
I believe copyright is the years you worked on it, and so the copyright period lasts for an additional 75 years after that date. At least that's the GNU recommendation - but happy to take alternative advice. 

I also have a CI so that once I make a commit in 2020 the CI will demand I update the copyright.

**Comment by umnikos** [comment]
Alright, I guess this was a pointless issue, then!
