### ISSUE TITLE
FYI: When stdin is not tty and -v0 is passed, GHCi doesn't print prompt.

### ISSUE THREAD

**Issue by phadej** [ndmitchell/ghcid#333]
https://gitlab.haskell.org/ghc/ghc/-/blob/cbc7c3dda6bdf4acb760ca9eb545faeb98ab0dbe/ghc/GHCi/UI.hs#L688-691

Related to https://github.com/ndmitchell/ghcid/blob/2c82ecf78b709a60ce7b3023ff6f49e01fa4275d/src/Language/Haskell/Ghcid.hs#L78

**Comment by ndmitchell** [comment]
Thanks for the info, I've updated the comment. In truth I'm not sure I care that much - it's pretty easy to filter out and since the initial workaround, I haven't had any issues. In contrast, passing `-v0` might have lots of unanticipated effects, so I'd rather avoid that without a lot of care and testing.
