### ISSUE TITLE
Issues with "Prelude.hs" in the same folder

### ISSUE THREAD

**Issue by Duta** [ndmitchell/ghcid#36]
### `Prelude.hs`
    module Prelude where

### `A.hs`
    module A where

* * *

# Situation 1 Structure:
    ./Prelude.hs
    ./A.hs
    ./.ghci

where `./.ghci` is

    :load A

* * *

# Situation 2 Structure:
    src/Prelude.hs
    src/A.hs
    ./.ghci

where `./.ghci` is

    :set -isrc
    :load A

* * *

Running `ghcid` in situation 1 gives: `ghcid.exe: UnexpectedExit "ghci" ""`

Running `ghcid` in situation 2 gets stuck in `Loading...` forever

**Comment by ndmitchell** [comment]
What's the use case for having `module Prelude where` in `Prelude.hs`? I'm just trying to understand why anyone does that. I can certainly imagine some of the things that go wrong if you do.

**Comment by Duta** [comment]
I was developing a file called `Prelude.hs`, it had more in it than that but it wasn't too relevant to the issue. Of course I can simply change the file name, but thought I'd mention.

**Comment by ndmitchell** [comment]
Were you calling the file `module Prelude` or some other name? My thoughts are it's a fairly obscure situation, and could be hard to avoid. We have to signal to GHCi that we've finished, for which we call `Prelude.putStrLn` and `Prelude.error`. If they aren't available, it's hard to make sure we flush stdout and stderr.

**Comment by Duta** [comment]
There were only issues when the file was called `Prelude.hs`, yeah. I realize it's obscure as hell, just noting it down.

**Comment by ndmitchell** [comment]
Thanks, I'll consider this unsupported but worth recording, unless anyone has any clever ideas.

**Comment by ndmitchell** [comment]
I think turning on package imports, doing import qualified "base" Prelude as MyUniquePreludeString, and then prodding MyUniquePreludeString should do it. The only issue is that turning on package imports might cause a program to work that otherwise didn't, so it's not free.

An alternative is to call `GHC.Err.error` (or something from `Control.Exception`) and `System.IO.putStrLn` so they don't clash with Prelude.

However, I have a feeling that people developing new Prelude's should call them MyPrelude.hs otherwise its going to get into a mess for all tools. And as such, not fixing anything might be the best approach.

**Comment by Duta** [comment]
Yeah, honestly I'd probably be in agreement re: not fixing. I wonder what tooling's like when hacking on _the_ Prelude

**Comment by ndmitchell** [comment]
I think making it harder to hack on _the_ Prelude is mostly a good thing :smile:.
