### ISSUE TITLE
Can't detect reloaded files when using `:set -package <PKG>`

### ISSUE THREAD

**Issue by cstrahan** [ndmitchell/ghcid#39]
I have the following lines in my `~/.ghci`:

    :set -package pretty-show
    :set -package hscolour

With those two lines present, when I `:reload` in ghci no message is printed, and ghcid then bails out because it can't detect any reloaded files.

Is this perhaps a problem that needs to reported upstream to GHC?

**Comment by cstrahan** [comment]
Using `ghcid -c 'cabal repl'` works... But I don't understand why.

**Comment by cstrahan** [comment]
... but then errors/warnings are shown only for the library in my cabal project, and not the executable - despite the `:l Main` in my `.ghci`.

**Comment by cstrahan** [comment]
So, `ghcid -c 'ghci'` fails when `~/.ghci` includes `:set -package pretty-show`, yet it works when `.ghci`  (and _not_ `~/.ghci`) includes `:set -package pretty-show`.

**Comment by ndmitchell** [comment]
`ghcid` assumes that if you have a `.ghci` file then instead of `cabal repl` it should start your project using `ghci`. However, in your case, running `ghci` just loads some packages and doesn't start your project. The contents of the `.ghci` file aren't the problem, merely that it exists at all. If you only have a `~/.ghci` then there is no `.ghci` file for `ghcid` to see and become confused by. There are two solutions:

* Use `-c 'cabal repl'`, which makes it explicit which file you should be using.
* Add `:load MainFile.hs` in your `.ghci` file so that running `ghci` alone loads up your project. That's what I do in all my projects, for example `ghcid` itself has a `.ghci` file with `:load`: https://github.com/ndmitchell/ghcid/blob/master/.ghci#L3

**Comment by cstrahan** [comment]
@ndmitchell 

I actually have this in my `.ghci`:

    :set -fwarn-unused-binds -fwarn-unused-imports
    :set -isrc
    :set -iboot
    :load Main

This is the pattern that I'm seeing: if I have the following lines in `~/.ghci`, ghci never prints the "reloading" messages:

    :set -package pretty-show
    :set -package hscolour

If I comment those lines (or remove `~/.ghci` entirely), ghci/ghcid work as expected.

I'm just trying to figure out where the problems lies: ghci or ghcid.

I assume you can repro this, if you put `:set -package <some-package-here>` in your `~/.ghci`?

-----

Oh, and thanks for `ghcid`! With my `~/.ghci` completely commented out (because everything else relies on those packages), `ghcid` works splendidly.

**Comment by cstrahan** [comment]
Ah, I think I see what's going on: `:set package` resets the set of loaded modules. I can see that's the case if I reorder the lines in `.ghci`. I presume that `~/.ghci` must be loaded _after_ `.ghci`, so the former resets the latter. If correct, I see two potential problems in ghci:

* The loaded modules shouldn't be reset after specifying a package
* `~/.ghci` should be loaded before `.ghci`

Assuming those are both valid, do you know where I should raise those two issues?

**Comment by ndmitchell** [comment]
The first is debatable - what if you reload a package that the loaded modules might have used or not. It would be nice if it worked, but it's not necessarily obvious that it should.

The second seems a definite bug, but is actually documented behaviuor https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci-dot-files.html. Perhaps the ".ghci master" can tell us why `~/.ghci` is consulted _after_ `./.ghci` rather than before, @chrisdone :).

**Comment by chrisdone** [comment]
I can't imagine why someone thought that was a good idea.

**Comment by ndmitchell** [comment]
@cstrahan So this sounds like a GHC bug, since the behaviour does seem nutty. With the latest release of ghcid I made it print out what its doing on startup, which should make it easier for people to diagnose the issue in future.

**Comment by ndmitchell** [comment]
OK, with the change in behaviour it's not as problematic and makes it clear what is happening, so closing.
