### ISSUE TITLE
Check executables in addition to library modules?

### ISSUE THREAD

**Issue by jtdaugherty** [ndmitchell/ghcid#41]
When I use `ghcid` I often want to know if my cabal file's `executable` entries will compile in addition to knowing whether library modules do.  Right now, since `ghcid` doesn't check those, I run `cabal install` or similar after `ghcid` ceases to report errors in order to check my entire package.  Would it be possible to make `ghcid` check my programs as well?  (Without running them, of course.)

**Comment by ndmitchell** [comment]
Hi @jtdaugherty - a reasonable request, and one that's already possible. All `ghcid` does it start `cabal repl` (if you have a `*.cabal` file but no `.ghci` file), and it's `cabal repl` that only loads your library. You can do either of:

* Pass arguments to `ghcid` such as `ghcid Test.Main` and it will import the module `Test.Main` with `cabal exec ghci`. Typically, the executable calls the library, so that way you test both.
* Write a `.ghci` file that loads everything you care about. Here is the [ghcid .ghci file](https://github.com/ndmitchell/ghcid/blob/master/.ghci), which loads the library and the test suite. Test that `ghci` puts the right things on your prompt, then `ghcid` will work for it too.

My hope is that `stack` will have some way of doing this better, loading the right set of things.

**Comment by jtdaugherty** [comment]
Okay. Thanks!
