### ISSUE TITLE
Allow `--test` to run in presence of warnings

### ISSUE THREAD

**Issue by mitchellwrosen** [ndmitchell/ghcid#66]
Currently the `-T` test will only run if there are no warnings or errors, but I often want to run the test even in the presence of warnings. I propose something along the lines of:

```
--test-pedantic=EXPR   // behavior of current --test=EXPR
--test=EXPR            // runs tests when countErrors = 0
```

**Comment by ndmitchell** [comment]
When you have warnings, but run the tests, they you are effectively hiding the warnings because the output gets replaced. As a result, I think having the default of only run the tests if there are no warnings is a good default. But if you want to run the test anyway, I'd think `-w` or similar as a flag might be best. I'm not a fan of giving the ability to run different tests based on the presence/absence of warnings, since that seems confusing.

**Comment by mitchellwrosen** [comment]
Hm. Would it be possible to show the warnings and also run the tests? Er, why does the output get replaced?

**Comment by ndmitchell** [comment]
If you put the warnings at the top of the console (which is desirable), then as soon as you get a single line of test output it's going to push the first line of warning off the console. I don't see any way to do it without going ncurses (which is significantly more complex and thus better to avoid).

**Comment by mitchellwrosen** [comment]
Oh, right. Well, the use case I had in mind was rapidly prototyping on some website or something, where the --test is just `":main"`. In this case, it's quite annoying when your site won't rebuild due to innocent warnings like unused variables, unused imports, etc. Yes, these can be hidden in `.ghci`, but that's also not ideal, as they should be dealt with eventually.

**Comment by ndmitchell** [comment]
Well I've added `-W` to run the tests even when there are warnings. As long as the test doesn't output too much it's not terrible to see the warnings, but certainly not idea, so it won't be the default.

**Comment by mitchellwrosen** [comment]
Thanks!
