### ISSUE TITLE
Reload not occuring when local stack dependency package changes

### ISSUE THREAD

**Issue by chrissound** [ndmitchell/ghcid#92]
I've got multiple local packages, where some packages (`A`, `B`) depends on `Common`, however if I modify `Common.hs` a file within `Common`, ghcid does not seem to do a `stack build` when I have executed `ghcid "--command=stack build;stack ghci A" --test="main"` with `foo/`

An example structure:
```
foo/
  stack.yaml
  A/
    Main.hs
    A.cabal
  B/
    Main.hs
    B.cabal
  Common/
    Common.hs
    Common.cabal
```

Running `stack ghci A`, does however initiate a build.

**Comment by ndmitchell** [comment]
You can certainly fix this manually by specifying `--restart=Common`. Given you are running `stack build` yourself as `--command` I'm not sure there is any other way `ghcid` could figure it out automatically.

I might suggest you do `stack build Common` instead of `stack build`, since that is likely to be slightly faster.

**Comment by ndmitchell** [comment]
Not possible, so closing.
